-- My Hospital Management System Creation
-- Steven Jones
-- ITC 341

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE BILL_ITEM CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE BILL CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TREATMENT_PLAN CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TREATMENT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE STAFF_ASSIGNMENT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ADMISSION CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ROOM CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PATIENT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DISEASE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE STAFF CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DEPARTMENT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- DEPARTMENT
-- Defines the different units in the hospital (Surgery, ICU, Ward, etc.)
CREATE TABLE DEPARTMENT (
    DeptID NUMBER PRIMARY KEY,
    DeptName VARCHAR2(100) NOT NULL UNIQUE,
    Description VARCHAR2(4000),
    Head_Doctor_StaffID NUMBER
    -- Head_Doctor_StaffID will be added after STAFF is created
);

-- ROOM
-- Defines the physical spaces that a patient could be in, including regular rooms, operating room's, and ICU's
CREATE TABLE ROOM (
    RoomNumber VARCHAR2(10) PRIMARY KEY,
    Room_Type VARCHAR2(50) NOT NULL,
    Room_Rate NUMBER(10,2) NOT NULL,
    DeptID NUMBER NOT NULL,
    Status VARCHAR2(20) DEFAULT 'Available' NOT NULL,
    CONSTRAINT FK_ROOM_DEPT FOREIGN KEY (DeptID) REFERENCES DEPARTMENT(DeptID)
);

-- STAFF
-- Consolidated entity for all personnel (Doctor, Nurse, Ward Boy, Admin)
CREATE TABLE STAFF (
  StaffID NUMBER PRIMARY KEY,
  First_Name VARCHAR2(50) NOT NULL,
  Last_Name VARCHAR2(50) NOT NULL,
  Role VARCHAR2(50) NOT NULL,
  Specialty VARCHAR2(100),
  Contact_Phone VARCHAR2(15),
  DeptID NUMBER NOT NULL,
  Supervisor_ID NUMBER,
  CONSTRAINT CHK_StaffRole CHECK (Role IN (
    'Doctor','Nurse','Ward Boy','Admin','Pharmacist','Lab Tech','Physio','Midwife',
    'Pharmacy Tech','Radiology Tech','Radiology Tech','Therapist'
  ))
);

ALTER TABLE DEPARTMENT
ADD CONSTRAINT FK_HeadDoctor
FOREIGN KEY (Head_Doctor_StaffID) REFERENCES STAFF(StaffID);

ALTER TABLE STAFF
  ADD CONSTRAINT FK_STAFF_DEPT FOREIGN KEY (DeptID) REFERENCES DEPARTMENT(DeptID);

ALTER TABLE STAFF
  ADD CONSTRAINT FK_STAFF_SUPERVISOR FOREIGN KEY (Supervisor_ID) REFERENCES STAFF(StaffID);

-- PATIENT
-- Stores personal details about each patient
CREATE TABLE PATIENT (
    PatientID NUMBER PRIMARY KEY,
    First_Name VARCHAR2(50) NOT NULL,
    Last_Name VARCHAR2(50) NOT NULL,
    Date_of_Birth DATE,
    Gender CHAR(1),
    Phone_Number VARCHAR2(15) NOT NULL,
    Address VARCHAR2(4000)
);

-- DISEASE
-- Catalogue of possible diagnoses
-- (I'm aware there is a difference between disease and other kinds of conditions, I just thought diseases would be easiest to refer to as)
CREATE TABLE DISEASE (
    DiseaseCode VARCHAR2(10) PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Description VARCHAR2(4000)
);

-- ADMISSION
-- The central entity, linking a patient, a room, and the medical condition
CREATE TABLE ADMISSION (
    AdmissionID NUMBER PRIMARY KEY,
    PatientID NUMBER NOT NULL,
    Admission_Date DATE NOT NULL,
    Discharge_Date DATE, -- Nullable until actual discharge happens
    RoomNumber VARCHAR2(10) NOT NULL,
    Primary_Diagnosis VARCHAR2(10) NOT NULL, -- Foreign Key to the main reason for admission
    CONSTRAINT FK_ADM_PATIENT FOREIGN KEY (PatientID) REFERENCES PATIENT(PatientID),
    CONSTRAINT FK_ADM_ROOM FOREIGN KEY (RoomNumber) REFERENCES ROOM(RoomNumber),
    CONSTRAINT FK_ADM_DISEASE FOREIGN KEY (Primary_Diagnosis) REFERENCES DISEASE(DiseaseCode)
);

-- STAFF_ASSIGNMENT
-- Links staff to specific roles
CREATE TABLE STAFF_ASSIGNMENT (
    StaffID NUMBER NOT NULL,
    AdmissionID NUMBER NOT NULL,
    Assignment_Role VARCHAR2(50) NOT NULL,
    Start_Date DATE NOT NULL,
    End_Date DATE
);

ALTER TABLE STAFF_ASSIGNMENT
  ADD CONSTRAINT PK_STAFF_ASSIGNMENT PRIMARY KEY (StaffID, AdmissionID);

ALTER TABLE STAFF_ASSIGNMENT
  ADD CONSTRAINT FK_SA_STAFF FOREIGN KEY (StaffID) REFERENCES STAFF(StaffID);

ALTER TABLE STAFF_ASSIGNMENT
  ADD CONSTRAINT FK_SA_ADMISSION FOREIGN KEY (AdmissionID) REFERENCES ADMISSION(AdmissionID);

-- TREATMENT
-- Defines the types of procedure/treatments available
CREATE TABLE TREATMENT (
    TreatmentID NUMBER PRIMARY KEY,
    Treatment_Name VARCHAR2(100) NOT NULL UNIQUE,
    Description VARCHAR2(4000),
    Base_Cost NUMBER(12,2) NOT NULL -- Cost of the procedure/treatment itself
);

-- TREATMENT_PLAN
-- Tracks which treatments are applied to a specific patient's admission
CREATE TABLE TREATMENT_PLAN (
    PlanID NUMBER,
    AdmissionID NUMBER NOT NULL,
    TreatmentID NUMBER NOT NULL,
    Date_Performed DATE NOT NULL,
    Notes VARCHAR2(4000)
);

ALTER TABLE TREATMENT_PLAN
  ADD CONSTRAINT PK_TREATMENT_PLAN PRIMARY KEY (PlanID);

ALTER TABLE TREATMENT_PLAN
  ADD CONSTRAINT FK_TP_ADMISSION FOREIGN KEY (AdmissionID) REFERENCES ADMISSION(AdmissionID);

ALTER TABLE TREATMENT_PLAN
  ADD CONSTRAINT FK_TP_TREATMENT FOREIGN KEY (TreatmentID) REFERENCES TREATMENT(TreatmentID);

-- BILL
-- Summary of the financial transaction of the hospital visit
CREATE TABLE BILL (
    BillID NUMBER PRIMARY KEY,
    AdmissionID NUMBER NOT NULL UNIQUE,
    Bill_Date DATE NOT NULL,
    Total_Amount NUMBER(12,2) DEFAULT 0.00,
    Status VARCHAR2(20) DEFAULT 'Pending' NOT NULL, -- Pending, Paid, or Partial
    CONSTRAINT FK_BILL_ADMISSION FOREIGN KEY (AdmissionID) REFERENCES ADMISSION(AdmissionID)
);

-- BILL_ITEM
-- Breakdown of all charges for a bill for a specific hospital visit
CREATE TABLE BILL_ITEM (
    BillItemID NUMBER PRIMARY KEY,
    BillID NUMBER NOT NULL,
    Item_Description VARCHAR2(255) NOT NULL,
    Item_Type VARCHAR2(50) NOT NULL,
    Quantity NUMBER NOT NULL,
    Unit_Price NUMBER(10,2) NOT NULL,
    Line_Total NUMBER(12,2) GENERATED ALWAYS AS (Quantity * Unit_Price) VIRTUAL,
    CONSTRAINT FK_BILLITEM_BILL FOREIGN KEY (BillID) REFERENCES BILL(BillID)
);